# -*- coding: utf-8 -*-
# This script was auto-generated by Sim4Life version 7.0.0.7019

import numpy
from s4l_v1.analysis import extractors, evaluators, viewers
import s4l_v1.document as document
import s4l_v1.units as units

try:
    # Creating the analysis pipeline
    # Adding a new ImageFieldImporter
    image_field_importer = extractors.ImageFieldImporter(inputs=[])
    image_field_importer.FileName = u"F:\\Data\\_Hummel\\4_data_for_modelling\\sub-61Y03\\ses-rs2\\dwi\\tensor_s4l.nii.gz"
    image_field_importer.UpdateAttributes()
    document.AllAlgorithms.Add(image_field_importer)

    # Adding a new ConductivityTensorMappingEvaluator
    inputs = [image_field_importer.Outputs["tensor_s4l.nii"]]
    conductivity_tensor_mapping_evaluator = (
        evaluators.ConductivityTensorMappingEvaluator(inputs=inputs)
    )
    conductivity_tensor_mapping_evaluator.UpdateAttributes()
    document.AllAlgorithms.Add(conductivity_tensor_mapping_evaluator)

    # Adding a new FractionAnisotropyEvaluator
    inputs = [image_field_importer.Outputs["tensor_s4l.nii"]]
    fraction_anisotropy_evaluator = evaluators.FractionAnisotropyEvaluator(
        inputs=inputs
    )
    fraction_anisotropy_evaluator.UpdateAttributes()
    document.AllAlgorithms.Add(fraction_anisotropy_evaluator)

    # Adding a new EigenVectorEvaluator
    inputs = [image_field_importer.Outputs["tensor_s4l.nii"]]
    eigen_vector_evaluator = evaluators.EigenVectorEvaluator(inputs=inputs)
    eigen_vector_evaluator.UpdateAttributes()
    document.AllAlgorithms.Add(eigen_vector_evaluator)

    # Adding a new SliceFieldViewer
    inputs = [fraction_anisotropy_evaluator.Outputs["FA"]]
    slice_field_viewer = viewers.SliceFieldViewer(inputs=inputs)
    slice_field_viewer.Visible = False
    slice_field_viewer.Data.Mode = slice_field_viewer.Data.Mode.enum.QuantityRealPart
    slice_field_viewer.Slice.Index = 41
    slice_field_viewer.UpdateAttributes()
    document.AllAlgorithms.Add(slice_field_viewer)

    # Adding a new VectorFieldViewer
    inputs = [eigen_vector_evaluator.Outputs["EV"]]
    vector_field_viewer = viewers.VectorFieldViewer(inputs=inputs)
    vector_field_viewer.Data.Phase = u"0°"
    vector_field_viewer.Vector.Plane.PlaneCenter = (
        numpy.array([-0.5699310302734375, -20.38001251220703, 42.400001525878906]),
        units.MilliMeters,
    )
    vector_field_viewer.Vector.Plane.Resolution = 200
    vector_field_viewer.Vector.ScaleArrows = True
    vector_field_viewer.Vector.ArrowSize = 5.0
    vector_field_viewer.UpdateAttributes()
    document.AllAlgorithms.Add(vector_field_viewer)

except Exception as exc:
    import traceback, sys

    traceback.print_exc(file=sys.stderr)
    # Reset active version to default
    raise (exc)
